// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicQuiz.Data;

#nullable disable

namespace MusicQuiz.Data.Data.Migrations
{
    [DbContext(typeof(MusicQuizDBContext))]
    partial class MusicQuizDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicQuiz.Data.Models.AudioFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("AudioData")
                        .IsRequired()
                        .HasColumnType("LONGBLOB");

                    b.HasKey("Id");

                    b.ToTable("AudioFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
