name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore Musiq_Quiz/Musiq_Quiz.sln  # Specify the solution file here
    
    - name: Build
      run: dotnet build Musiq_Quiz/Musiq_Quiz.sln --no-restore  # Specify the solution file here
    
    - name: Test
      run: dotnet test Musiq_Quiz/Musiq_Quiz.sln --no-build --verbosity normal  # Specify the solution file here
